export enum LoadPostsActionType {
  LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST',
  LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS',
  LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE',
}

export enum AddPostActionType {
  ADD_POST_REQUEST = 'ADD_POST_REQUEST',
  ADD_POST_SUCCESS = 'ADD_POST_SUCCESS',
  ADD_POST_FAILURE = 'ADD_POST_FAILURE',
}

export enum RemovePostActionType {
  REMOVE_POST_REQUEST = 'REMOVE_POST_REQUEST',
  REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS',
  REMOVE_POST_FAILURE = 'REMOVE_POST_FAILURE',
}

export enum AddCommentActionType {
  ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST',
  ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE',
}

export enum RemoveCommentActionType {
  REMOVE_COMMENT_REQUEST = 'REMOVE_COMMENT_REQUEST',
  REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS',
  REMOVE_COMMENT_FAILURE = 'REMOVE_COMMENT_FAILURE',
}

export enum LikePostActionType {
    LIKE_POST_REQUEST = 'LIKE_POST_REQUEST',
    LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS',
    LIKE_POST_FAILURE = 'LIKE_POST_FAILURE',
}

export enum UnlikePostActionType {
  UNLIKE_POST_REQUEST = 'UNLIKE_POST_REQUEST',
  UNLIKE_POST_SUCCESS = 'UNLIKE_POST_SUCCESS',
  UNLIKE_POST_FAILURE = 'UNLIKE_POST_FAILURE',
}