export enum LogInActionType {
  LOG_IN_REQUEST = 'LOG_IN_REQUEST',
  LOG_IN_SUCCESS = 'LOG_IN_SUCCESS',
  LOG_IN_FAILURE = 'LOG_IN_FAILURE',
}

export enum LogOutActionType {
  LOG_OUT_REQUEST = 'LOG_OUT_REQUEST',
  LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS',
  LOG_OUT_FAILURE = 'LOG_OUT_FAILURE',
}

export enum SignUpActionType {
  SIGN_UP_REQUEST = 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE = 'SIGN_UP_FAILURE',
}

export enum FollowActionType {
  FOLLOW_REQUEST = 'FOLLOW_REQUEST',
  FOLLOW_SUCCESS = 'FOLLOW_SUCCESS',
  FOLLOW_FAILURE = 'FOLLOW_FAILURE',
}

export enum UnfollowActionType {
  UNFOLLOW_REQUEST = 'UNFOLLOW_REQUEST',
  UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS',
  UNFOLLOW_FAILURE = 'UNFOLLOW_FAILURE',
}

export enum ChangeNicknameActionType {
  CHANGE_NICKNAME_REQUEST = 'CHANGE_NICKNAME_REQUEST',
  CHANGE_NICKNAME_SUCCESS = 'CHANGE_NICKNAME_SUCCESS',
  CHANGE_NICKNAME_FAILURE = 'CHANGE_NICKNAME_FAILURE',
}

export enum AddPostToMeActionType {
  ADD_POST_TO_ME = 'ADD_POST_TO_ME'
}

export enum RemovePostOfMeActionType {
  REMOVE_POST_OF_ME = 'REMOVE_POST_OF_ME'
}

export enum NavigateProfileActionType {
  NAVIGATE_PROFILE = 'NAVIGATE_PROFILE'
}